name: Duster Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  duster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: "Duster Lint"
        uses: tighten/duster-action@557d11cf6d55a7f7cf6324806c633af0062759eb # v3
        with:
          args: lint
